# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f7d7e1722c3089a7091cdb17c979b7249df6409a6764fbed4827710019ecab75896f423555a257865e93c2329655d2aab67169366aae1d9f3386d70f4616982

test:
  secret_key_base: 48e78644e4947a358b8b9f41aba1a84acabdf36ee633e3e058f6962bde4b796835220d9289aadd4411a0190271c76032eeed65cb675004c592d443ec9a2dc957

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
